# Generated by Django 3.2.6 on 2021-08-26 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('phone1', models.IntegerField()),
                ('c_add', models.CharField(max_length=100)),
                ('c_city', models.CharField(max_length=100)),
                ('c_state', models.CharField(max_length=150)),
                ('c_zip', models.IntegerField()),
                ('p_add', models.CharField(max_length=100)),
                ('p_city', models.CharField(max_length=100)),
                ('p_state', models.CharField(max_length=150)),
                ('p_zip', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('messagees', models.TextField(max_length=500)),
                ('a_date_time', models.DateTimeField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
