# Generated by Django 3.2.6 on 2021-08-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Appointment',
        ),
    ]
